[package]
name = "frontend"
version = "0.1.0"
authors = ["Kevin Oberlies <favilo@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Frontend for raspylights"
categories = ["hardware"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
wasm-bindgen-test = "0.3.18"

[dependencies]
# enum-iterator = "0.6.0"
lights = { path = "../lights" }
serde = { version = "1.0.120", features = ["derive"] }
strum = "0.20.0"
strum_macros = "0.20.1"
wasm-bindgen = "0.2.69"
yew = "0.17.4"
wasm-logger = "0.2.0"
log = "0.4.13"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
