[package]
name = "lights"
version = "0.1.0"
authors = ["Kevin Oberlies <favilo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
palette = "0.5.0"
serde = { version = "1.0.118", features = ["derive"] }
# rs_ws281x = { git = "https://github.com/favilo/rpi-ws281x-rust", branch = "master" }
log = "0.4.11"
itertools = "0.10.0"
thiserror = "1.0.23"
enum-iterator = "0.6.0"
enum_derive = "0.1.7"
instant = { version = "0.1.9", features = ["now", "wasm-bindgen"] }
mopa = "0.2.2"
